/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the IdpToSpAdapterMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdpToSpAdapterMapping{}

// IdpToSpAdapterMapping The IdP-to-SP Adapter Mapping.
type IdpToSpAdapterMapping struct {
	// A list of configured data stores to look up attributes from.
	AttributeSources []AttributeSource `json:"attributeSources,omitempty" tfsdk:"attribute_sources"`
	// A list of mappings from attribute names to their fulfillment values.
	AttributeContractFulfillment map[string]AttributeFulfillmentValue `json:"attributeContractFulfillment" tfsdk:"attribute_contract_fulfillment"`
	IssuanceCriteria             *IssuanceCriteria                    `json:"issuanceCriteria,omitempty" tfsdk:"issuance_criteria"`
	// The id of the IdP Adapter.
	SourceId string `json:"sourceId" tfsdk:"source_id"`
	// The id of the SP Adapter.
	TargetId string `json:"targetId" tfsdk:"target_id"`
	// The id of the IdP-to-SP Adapter mapping. This field is read-only and is ignored when passed in with the payload.
	Id *string `json:"id,omitempty" tfsdk:"id"`
	// Default target URL for this adapter-to-adapter mapping configuration.
	DefaultTargetResource *string `json:"defaultTargetResource,omitempty" tfsdk:"default_target_resource"`
	// The license connection group.
	LicenseConnectionGroupAssignment *string `json:"licenseConnectionGroupAssignment,omitempty" tfsdk:"license_connection_group_assignment"`
	// The application name.
	ApplicationName *string `json:"applicationName,omitempty" tfsdk:"application_name"`
	// The application icon URL.
	ApplicationIconUrl *string `json:"applicationIconUrl,omitempty" tfsdk:"application_icon_url"`
}

// NewIdpToSpAdapterMapping instantiates a new IdpToSpAdapterMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdpToSpAdapterMapping(attributeContractFulfillment map[string]AttributeFulfillmentValue, sourceId string, targetId string) *IdpToSpAdapterMapping {
	this := IdpToSpAdapterMapping{}
	this.AttributeContractFulfillment = attributeContractFulfillment
	this.SourceId = sourceId
	this.TargetId = targetId
	return &this
}

// NewIdpToSpAdapterMappingWithDefaults instantiates a new IdpToSpAdapterMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdpToSpAdapterMappingWithDefaults() *IdpToSpAdapterMapping {
	this := IdpToSpAdapterMapping{}
	return &this
}

// GetAttributeSources returns the AttributeSources field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetAttributeSources() []AttributeSource {
	if o == nil || IsNil(o.AttributeSources) {
		var ret []AttributeSource
		return ret
	}
	return o.AttributeSources
}

// GetAttributeSourcesOk returns a tuple with the AttributeSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetAttributeSourcesOk() ([]AttributeSource, bool) {
	if o == nil || IsNil(o.AttributeSources) {
		return nil, false
	}
	return o.AttributeSources, true
}

// HasAttributeSources returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasAttributeSources() bool {
	if o != nil && !IsNil(o.AttributeSources) {
		return true
	}

	return false
}

// SetAttributeSources gets a reference to the given []AttributeSource and assigns it to the AttributeSources field.
func (o *IdpToSpAdapterMapping) SetAttributeSources(v []AttributeSource) {
	o.AttributeSources = v
}

// GetAttributeContractFulfillment returns the AttributeContractFulfillment field value
func (o *IdpToSpAdapterMapping) GetAttributeContractFulfillment() map[string]AttributeFulfillmentValue {
	if o == nil {
		var ret map[string]AttributeFulfillmentValue
		return ret
	}

	return o.AttributeContractFulfillment
}

// GetAttributeContractFulfillmentOk returns a tuple with the AttributeContractFulfillment field value
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetAttributeContractFulfillmentOk() (*map[string]AttributeFulfillmentValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeContractFulfillment, true
}

// SetAttributeContractFulfillment sets field value
func (o *IdpToSpAdapterMapping) SetAttributeContractFulfillment(v map[string]AttributeFulfillmentValue) {
	o.AttributeContractFulfillment = v
}

// GetIssuanceCriteria returns the IssuanceCriteria field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetIssuanceCriteria() IssuanceCriteria {
	if o == nil || IsNil(o.IssuanceCriteria) {
		var ret IssuanceCriteria
		return ret
	}
	return *o.IssuanceCriteria
}

// GetIssuanceCriteriaOk returns a tuple with the IssuanceCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetIssuanceCriteriaOk() (*IssuanceCriteria, bool) {
	if o == nil || IsNil(o.IssuanceCriteria) {
		return nil, false
	}
	return o.IssuanceCriteria, true
}

// HasIssuanceCriteria returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasIssuanceCriteria() bool {
	if o != nil && !IsNil(o.IssuanceCriteria) {
		return true
	}

	return false
}

// SetIssuanceCriteria gets a reference to the given IssuanceCriteria and assigns it to the IssuanceCriteria field.
func (o *IdpToSpAdapterMapping) SetIssuanceCriteria(v IssuanceCriteria) {
	o.IssuanceCriteria = &v
}

// GetSourceId returns the SourceId field value
func (o *IdpToSpAdapterMapping) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *IdpToSpAdapterMapping) SetSourceId(v string) {
	o.SourceId = v
}

// GetTargetId returns the TargetId field value
func (o *IdpToSpAdapterMapping) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *IdpToSpAdapterMapping) SetTargetId(v string) {
	o.TargetId = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IdpToSpAdapterMapping) SetId(v string) {
	o.Id = &v
}

// GetDefaultTargetResource returns the DefaultTargetResource field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetDefaultTargetResource() string {
	if o == nil || IsNil(o.DefaultTargetResource) {
		var ret string
		return ret
	}
	return *o.DefaultTargetResource
}

// GetDefaultTargetResourceOk returns a tuple with the DefaultTargetResource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetDefaultTargetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTargetResource) {
		return nil, false
	}
	return o.DefaultTargetResource, true
}

// HasDefaultTargetResource returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasDefaultTargetResource() bool {
	if o != nil && !IsNil(o.DefaultTargetResource) {
		return true
	}

	return false
}

// SetDefaultTargetResource gets a reference to the given string and assigns it to the DefaultTargetResource field.
func (o *IdpToSpAdapterMapping) SetDefaultTargetResource(v string) {
	o.DefaultTargetResource = &v
}

// GetLicenseConnectionGroupAssignment returns the LicenseConnectionGroupAssignment field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetLicenseConnectionGroupAssignment() string {
	if o == nil || IsNil(o.LicenseConnectionGroupAssignment) {
		var ret string
		return ret
	}
	return *o.LicenseConnectionGroupAssignment
}

// GetLicenseConnectionGroupAssignmentOk returns a tuple with the LicenseConnectionGroupAssignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetLicenseConnectionGroupAssignmentOk() (*string, bool) {
	if o == nil || IsNil(o.LicenseConnectionGroupAssignment) {
		return nil, false
	}
	return o.LicenseConnectionGroupAssignment, true
}

// HasLicenseConnectionGroupAssignment returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasLicenseConnectionGroupAssignment() bool {
	if o != nil && !IsNil(o.LicenseConnectionGroupAssignment) {
		return true
	}

	return false
}

// SetLicenseConnectionGroupAssignment gets a reference to the given string and assigns it to the LicenseConnectionGroupAssignment field.
func (o *IdpToSpAdapterMapping) SetLicenseConnectionGroupAssignment(v string) {
	o.LicenseConnectionGroupAssignment = &v
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetApplicationName() string {
	if o == nil || IsNil(o.ApplicationName) {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetApplicationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationName) {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasApplicationName() bool {
	if o != nil && !IsNil(o.ApplicationName) {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *IdpToSpAdapterMapping) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetApplicationIconUrl returns the ApplicationIconUrl field value if set, zero value otherwise.
func (o *IdpToSpAdapterMapping) GetApplicationIconUrl() string {
	if o == nil || IsNil(o.ApplicationIconUrl) {
		var ret string
		return ret
	}
	return *o.ApplicationIconUrl
}

// GetApplicationIconUrlOk returns a tuple with the ApplicationIconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpToSpAdapterMapping) GetApplicationIconUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationIconUrl) {
		return nil, false
	}
	return o.ApplicationIconUrl, true
}

// HasApplicationIconUrl returns a boolean if a field has been set.
func (o *IdpToSpAdapterMapping) HasApplicationIconUrl() bool {
	if o != nil && !IsNil(o.ApplicationIconUrl) {
		return true
	}

	return false
}

// SetApplicationIconUrl gets a reference to the given string and assigns it to the ApplicationIconUrl field.
func (o *IdpToSpAdapterMapping) SetApplicationIconUrl(v string) {
	o.ApplicationIconUrl = &v
}

func (o IdpToSpAdapterMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdpToSpAdapterMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeSources) {
		toSerialize["attributeSources"] = o.AttributeSources
	}
	toSerialize["attributeContractFulfillment"] = o.AttributeContractFulfillment
	if !IsNil(o.IssuanceCriteria) {
		toSerialize["issuanceCriteria"] = o.IssuanceCriteria
	}
	toSerialize["sourceId"] = o.SourceId
	toSerialize["targetId"] = o.TargetId
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.DefaultTargetResource) {
		toSerialize["defaultTargetResource"] = o.DefaultTargetResource
	}
	if !IsNil(o.LicenseConnectionGroupAssignment) {
		toSerialize["licenseConnectionGroupAssignment"] = o.LicenseConnectionGroupAssignment
	}
	if !IsNil(o.ApplicationName) {
		toSerialize["applicationName"] = o.ApplicationName
	}
	if !IsNil(o.ApplicationIconUrl) {
		toSerialize["applicationIconUrl"] = o.ApplicationIconUrl
	}
	return toSerialize, nil
}

type NullableIdpToSpAdapterMapping struct {
	value *IdpToSpAdapterMapping
	isSet bool
}

func (v NullableIdpToSpAdapterMapping) Get() *IdpToSpAdapterMapping {
	return v.value
}

func (v *NullableIdpToSpAdapterMapping) Set(val *IdpToSpAdapterMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableIdpToSpAdapterMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableIdpToSpAdapterMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdpToSpAdapterMapping(val *IdpToSpAdapterMapping) *NullableIdpToSpAdapterMapping {
	return &NullableIdpToSpAdapterMapping{value: val, isSet: true}
}

func (v NullableIdpToSpAdapterMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdpToSpAdapterMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
