/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 12.0.0.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the ApcToPersistentGrantMappings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApcToPersistentGrantMappings{}

// ApcToPersistentGrantMappings A collection of OAuth authentication policy contract to persistent grant mapping items.
type ApcToPersistentGrantMappings struct {
	// The actual list of OAuth authentication policy contract to persistent grant mappings.
	Items []ApcToPersistentGrantMapping `json:"items,omitempty" tfsdk:"items"`
}

// NewApcToPersistentGrantMappings instantiates a new ApcToPersistentGrantMappings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApcToPersistentGrantMappings() *ApcToPersistentGrantMappings {
	this := ApcToPersistentGrantMappings{}
	return &this
}

// NewApcToPersistentGrantMappingsWithDefaults instantiates a new ApcToPersistentGrantMappings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApcToPersistentGrantMappingsWithDefaults() *ApcToPersistentGrantMappings {
	this := ApcToPersistentGrantMappings{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ApcToPersistentGrantMappings) GetItems() []ApcToPersistentGrantMapping {
	if o == nil || IsNil(o.Items) {
		var ret []ApcToPersistentGrantMapping
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApcToPersistentGrantMappings) GetItemsOk() ([]ApcToPersistentGrantMapping, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ApcToPersistentGrantMappings) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ApcToPersistentGrantMapping and assigns it to the Items field.
func (o *ApcToPersistentGrantMappings) SetItems(v []ApcToPersistentGrantMapping) {
	o.Items = v
}

func (o ApcToPersistentGrantMappings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApcToPersistentGrantMappings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableApcToPersistentGrantMappings struct {
	value *ApcToPersistentGrantMappings
	isSet bool
}

func (v NullableApcToPersistentGrantMappings) Get() *ApcToPersistentGrantMappings {
	return v.value
}

func (v *NullableApcToPersistentGrantMappings) Set(val *ApcToPersistentGrantMappings) {
	v.value = val
	v.isSet = true
}

func (v NullableApcToPersistentGrantMappings) IsSet() bool {
	return v.isSet
}

func (v *NullableApcToPersistentGrantMappings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApcToPersistentGrantMappings(val *ApcToPersistentGrantMappings) *NullableApcToPersistentGrantMappings {
	return &NullableApcToPersistentGrantMappings{value: val, isSet: true}
}

func (v NullableApcToPersistentGrantMappings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApcToPersistentGrantMappings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
