/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the IdpAdapterAssertionMappingAdapterOverrideSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdpAdapterAssertionMappingAdapterOverrideSettings{}

// IdpAdapterAssertionMappingAdapterOverrideSettings struct for IdpAdapterAssertionMappingAdapterOverrideSettings
type IdpAdapterAssertionMappingAdapterOverrideSettings struct {
	// The ID of the plugin instance. The ID cannot be modified once the instance is created.<br>Note: Ignored when specifying a connection's adapter override.
	Id interface{} `json:"id" tfsdk:"id"`
	// The plugin instance name. The name can be modified once the instance is created.<br>Note: Ignored when specifying a connection's adapter override.
	Name                interface{}         `json:"name" tfsdk:"name"`
	PluginDescriptorRef ResourceLink        `json:"pluginDescriptorRef" tfsdk:"plugin_descriptor_ref"`
	ParentRef           *ResourceLink       `json:"parentRef,omitempty" tfsdk:"parent_ref"`
	Configuration       PluginConfiguration `json:"configuration" tfsdk:"configuration"`
	// The fixed value that indicates how the user was authenticated.
	AuthnCtxClassRef  interface{}                  `json:"authnCtxClassRef,omitempty" tfsdk:"authn_ctx_class_ref"`
	AttributeMapping  *IdpAdapterContractMapping   `json:"attributeMapping,omitempty" tfsdk:"attribute_mapping"`
	AttributeContract *IdpAdapterAttributeContract `json:"attributeContract,omitempty" tfsdk:"attribute_contract"`
}

// NewIdpAdapterAssertionMappingAdapterOverrideSettings instantiates a new IdpAdapterAssertionMappingAdapterOverrideSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdpAdapterAssertionMappingAdapterOverrideSettings(id interface{}, name interface{}, pluginDescriptorRef ResourceLink, configuration PluginConfiguration) *IdpAdapterAssertionMappingAdapterOverrideSettings {
	this := IdpAdapterAssertionMappingAdapterOverrideSettings{}
	this.Id = id
	this.Name = name
	this.PluginDescriptorRef = pluginDescriptorRef
	this.Configuration = configuration
	return &this
}

// NewIdpAdapterAssertionMappingAdapterOverrideSettingsWithDefaults instantiates a new IdpAdapterAssertionMappingAdapterOverrideSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdpAdapterAssertionMappingAdapterOverrideSettingsWithDefaults() *IdpAdapterAssertionMappingAdapterOverrideSettings {
	this := IdpAdapterAssertionMappingAdapterOverrideSettings{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetId(v interface{}) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetName(v interface{}) {
	o.Name = v
}

// GetPluginDescriptorRef returns the PluginDescriptorRef field value
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetPluginDescriptorRef() ResourceLink {
	if o == nil {
		var ret ResourceLink
		return ret
	}

	return o.PluginDescriptorRef
}

// GetPluginDescriptorRefOk returns a tuple with the PluginDescriptorRef field value
// and a boolean to check if the value has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetPluginDescriptorRefOk() (*ResourceLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PluginDescriptorRef, true
}

// SetPluginDescriptorRef sets field value
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetPluginDescriptorRef(v ResourceLink) {
	o.PluginDescriptorRef = v
}

// GetParentRef returns the ParentRef field value if set, zero value otherwise.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetParentRef() ResourceLink {
	if o == nil || IsNil(o.ParentRef) {
		var ret ResourceLink
		return ret
	}
	return *o.ParentRef
}

// GetParentRefOk returns a tuple with the ParentRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetParentRefOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.ParentRef) {
		return nil, false
	}
	return o.ParentRef, true
}

// HasParentRef returns a boolean if a field has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) HasParentRef() bool {
	if o != nil && !IsNil(o.ParentRef) {
		return true
	}

	return false
}

// SetParentRef gets a reference to the given ResourceLink and assigns it to the ParentRef field.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetParentRef(v ResourceLink) {
	o.ParentRef = &v
}

// GetConfiguration returns the Configuration field value
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetConfiguration() PluginConfiguration {
	if o == nil {
		var ret PluginConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetConfigurationOk() (*PluginConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetConfiguration(v PluginConfiguration) {
	o.Configuration = v
}

// GetAuthnCtxClassRef returns the AuthnCtxClassRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetAuthnCtxClassRef() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AuthnCtxClassRef
}

// GetAuthnCtxClassRefOk returns a tuple with the AuthnCtxClassRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetAuthnCtxClassRefOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AuthnCtxClassRef) {
		return nil, false
	}
	return &o.AuthnCtxClassRef, true
}

// HasAuthnCtxClassRef returns a boolean if a field has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) HasAuthnCtxClassRef() bool {
	if o != nil && IsNil(o.AuthnCtxClassRef) {
		return true
	}

	return false
}

// SetAuthnCtxClassRef gets a reference to the given interface{} and assigns it to the AuthnCtxClassRef field.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetAuthnCtxClassRef(v interface{}) {
	o.AuthnCtxClassRef = v
}

// GetAttributeMapping returns the AttributeMapping field value if set, zero value otherwise.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetAttributeMapping() IdpAdapterContractMapping {
	if o == nil || IsNil(o.AttributeMapping) {
		var ret IdpAdapterContractMapping
		return ret
	}
	return *o.AttributeMapping
}

// GetAttributeMappingOk returns a tuple with the AttributeMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetAttributeMappingOk() (*IdpAdapterContractMapping, bool) {
	if o == nil || IsNil(o.AttributeMapping) {
		return nil, false
	}
	return o.AttributeMapping, true
}

// HasAttributeMapping returns a boolean if a field has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) HasAttributeMapping() bool {
	if o != nil && !IsNil(o.AttributeMapping) {
		return true
	}

	return false
}

// SetAttributeMapping gets a reference to the given IdpAdapterContractMapping and assigns it to the AttributeMapping field.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetAttributeMapping(v IdpAdapterContractMapping) {
	o.AttributeMapping = &v
}

// GetAttributeContract returns the AttributeContract field value if set, zero value otherwise.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetAttributeContract() IdpAdapterAttributeContract {
	if o == nil || IsNil(o.AttributeContract) {
		var ret IdpAdapterAttributeContract
		return ret
	}
	return *o.AttributeContract
}

// GetAttributeContractOk returns a tuple with the AttributeContract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) GetAttributeContractOk() (*IdpAdapterAttributeContract, bool) {
	if o == nil || IsNil(o.AttributeContract) {
		return nil, false
	}
	return o.AttributeContract, true
}

// HasAttributeContract returns a boolean if a field has been set.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) HasAttributeContract() bool {
	if o != nil && !IsNil(o.AttributeContract) {
		return true
	}

	return false
}

// SetAttributeContract gets a reference to the given IdpAdapterAttributeContract and assigns it to the AttributeContract field.
func (o *IdpAdapterAssertionMappingAdapterOverrideSettings) SetAttributeContract(v IdpAdapterAttributeContract) {
	o.AttributeContract = &v
}

func (o IdpAdapterAssertionMappingAdapterOverrideSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdpAdapterAssertionMappingAdapterOverrideSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	toSerialize["pluginDescriptorRef"] = o.PluginDescriptorRef
	if !IsNil(o.ParentRef) {
		toSerialize["parentRef"] = o.ParentRef
	}
	toSerialize["configuration"] = o.Configuration
	if o.AuthnCtxClassRef != nil {
		toSerialize["authnCtxClassRef"] = o.AuthnCtxClassRef
	}
	if !IsNil(o.AttributeMapping) {
		toSerialize["attributeMapping"] = o.AttributeMapping
	}
	if !IsNil(o.AttributeContract) {
		toSerialize["attributeContract"] = o.AttributeContract
	}
	return toSerialize, nil
}

type NullableIdpAdapterAssertionMappingAdapterOverrideSettings struct {
	value *IdpAdapterAssertionMappingAdapterOverrideSettings
	isSet bool
}

func (v NullableIdpAdapterAssertionMappingAdapterOverrideSettings) Get() *IdpAdapterAssertionMappingAdapterOverrideSettings {
	return v.value
}

func (v *NullableIdpAdapterAssertionMappingAdapterOverrideSettings) Set(val *IdpAdapterAssertionMappingAdapterOverrideSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableIdpAdapterAssertionMappingAdapterOverrideSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableIdpAdapterAssertionMappingAdapterOverrideSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdpAdapterAssertionMappingAdapterOverrideSettings(val *IdpAdapterAssertionMappingAdapterOverrideSettings) *NullableIdpAdapterAssertionMappingAdapterOverrideSettings {
	return &NullableIdpAdapterAssertionMappingAdapterOverrideSettings{value: val, isSet: true}
}

func (v NullableIdpAdapterAssertionMappingAdapterOverrideSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdpAdapterAssertionMappingAdapterOverrideSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
