/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 12.0.0.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the CustomDataStoreDescriptors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDataStoreDescriptors{}

// CustomDataStoreDescriptors A collection of custom data store descriptors.
type CustomDataStoreDescriptors struct {
	// The list of custom data store descriptors.
	Items []CustomDataStoreDescriptor `json:"items,omitempty" tfsdk:"items"`
}

// NewCustomDataStoreDescriptors instantiates a new CustomDataStoreDescriptors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDataStoreDescriptors() *CustomDataStoreDescriptors {
	this := CustomDataStoreDescriptors{}
	return &this
}

// NewCustomDataStoreDescriptorsWithDefaults instantiates a new CustomDataStoreDescriptors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDataStoreDescriptorsWithDefaults() *CustomDataStoreDescriptors {
	this := CustomDataStoreDescriptors{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CustomDataStoreDescriptors) GetItems() []CustomDataStoreDescriptor {
	if o == nil || IsNil(o.Items) {
		var ret []CustomDataStoreDescriptor
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomDataStoreDescriptors) GetItemsOk() ([]CustomDataStoreDescriptor, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CustomDataStoreDescriptors) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CustomDataStoreDescriptor and assigns it to the Items field.
func (o *CustomDataStoreDescriptors) SetItems(v []CustomDataStoreDescriptor) {
	o.Items = v
}

func (o CustomDataStoreDescriptors) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDataStoreDescriptors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCustomDataStoreDescriptors struct {
	value *CustomDataStoreDescriptors
	isSet bool
}

func (v NullableCustomDataStoreDescriptors) Get() *CustomDataStoreDescriptors {
	return v.value
}

func (v *NullableCustomDataStoreDescriptors) Set(val *CustomDataStoreDescriptors) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDataStoreDescriptors) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDataStoreDescriptors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDataStoreDescriptors(val *CustomDataStoreDescriptors) *NullableCustomDataStoreDescriptors {
	return &NullableCustomDataStoreDescriptors{value: val, isSet: true}
}

func (v NullableCustomDataStoreDescriptors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDataStoreDescriptors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
