/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 12.0.0.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the CaptchaProviders type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptchaProviders{}

// CaptchaProviders A collection of CAPTCHA provider plugin instances.
type CaptchaProviders struct {
	// The list of CAPTCHA provider plugin instances.
	Items []CaptchaProvider `json:"items,omitempty" tfsdk:"items"`
}

// NewCaptchaProviders instantiates a new CaptchaProviders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptchaProviders() *CaptchaProviders {
	this := CaptchaProviders{}
	return &this
}

// NewCaptchaProvidersWithDefaults instantiates a new CaptchaProviders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptchaProvidersWithDefaults() *CaptchaProviders {
	this := CaptchaProviders{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CaptchaProviders) GetItems() []CaptchaProvider {
	if o == nil || IsNil(o.Items) {
		var ret []CaptchaProvider
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptchaProviders) GetItemsOk() ([]CaptchaProvider, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CaptchaProviders) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CaptchaProvider and assigns it to the Items field.
func (o *CaptchaProviders) SetItems(v []CaptchaProvider) {
	o.Items = v
}

func (o CaptchaProviders) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptchaProviders) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCaptchaProviders struct {
	value *CaptchaProviders
	isSet bool
}

func (v NullableCaptchaProviders) Get() *CaptchaProviders {
	return v.value
}

func (v *NullableCaptchaProviders) Set(val *CaptchaProviders) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptchaProviders) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptchaProviders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptchaProviders(val *CaptchaProviders) *NullableCaptchaProviders {
	return &NullableCaptchaProviders{value: val, isSet: true}
}

func (v NullableCaptchaProviders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptchaProviders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
