/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 12.0.0.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the CheckBoxFieldDescriptor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckBoxFieldDescriptor{}

// CheckBoxFieldDescriptor struct for CheckBoxFieldDescriptor
type CheckBoxFieldDescriptor struct {
	FieldDescriptor
}

// NewCheckBoxFieldDescriptor instantiates a new CheckBoxFieldDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckBoxFieldDescriptor() *CheckBoxFieldDescriptor {
	this := CheckBoxFieldDescriptor{}
	return &this
}

// NewCheckBoxFieldDescriptorWithDefaults instantiates a new CheckBoxFieldDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckBoxFieldDescriptorWithDefaults() *CheckBoxFieldDescriptor {
	this := CheckBoxFieldDescriptor{}
	return &this
}

func (o CheckBoxFieldDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckBoxFieldDescriptor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedFieldDescriptor, errFieldDescriptor := json.Marshal(o.FieldDescriptor)
	if errFieldDescriptor != nil {
		return map[string]interface{}{}, errFieldDescriptor
	}
	errFieldDescriptor = json.Unmarshal([]byte(serializedFieldDescriptor), &toSerialize)
	if errFieldDescriptor != nil {
		return map[string]interface{}{}, errFieldDescriptor
	}
	return toSerialize, nil
}

type NullableCheckBoxFieldDescriptor struct {
	value *CheckBoxFieldDescriptor
	isSet bool
}

func (v NullableCheckBoxFieldDescriptor) Get() *CheckBoxFieldDescriptor {
	return v.value
}

func (v *NullableCheckBoxFieldDescriptor) Set(val *CheckBoxFieldDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckBoxFieldDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckBoxFieldDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckBoxFieldDescriptor(val *CheckBoxFieldDescriptor) *NullableCheckBoxFieldDescriptor {
	return &NullableCheckBoxFieldDescriptor{value: val, isSet: true}
}

func (v NullableCheckBoxFieldDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckBoxFieldDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
