// Copyright © 2026 Ping Identity Corporation

/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 13.1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the TagUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagUsage{}

// TagUsage Information about which resources currently reference a tag.
type TagUsage struct {
	// The number of OAuth clients that reference this tag.
	ClientCount *int64 `json:"clientCount,omitempty" tfsdk:"client_count"`
	// IDs of OAuth clients that reference this tag.
	ClientIds []string `json:"clientIds,omitempty" tfsdk:"client_ids"`
	// Authentication selector instances that reference this tag. Deletion is blocked while non-empty.
	SelectorInstances []ReferenceItem `json:"selectorInstances,omitempty" tfsdk:"selector_instances"`
	// CIMD policies that reference this tag. Deletion is blocked while non-empty.
	CimdPolicies []ReferenceItem `json:"cimdPolicies,omitempty" tfsdk:"cimd_policies"`
	// Whether OAuth client settings reference this tag. Deletion is blocked when true.
	ClientSettingsUsed *bool `json:"clientSettingsUsed,omitempty" tfsdk:"client_settings_used"`
}

// NewTagUsage instantiates a new TagUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagUsage() *TagUsage {
	this := TagUsage{}
	return &this
}

// NewTagUsageWithDefaults instantiates a new TagUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagUsageWithDefaults() *TagUsage {
	this := TagUsage{}
	return &this
}

// GetClientCount returns the ClientCount field value if set, zero value otherwise.
func (o *TagUsage) GetClientCount() int64 {
	if o == nil || IsNil(o.ClientCount) {
		var ret int64
		return ret
	}
	return *o.ClientCount
}

// GetClientCountOk returns a tuple with the ClientCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagUsage) GetClientCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ClientCount) {
		return nil, false
	}
	return o.ClientCount, true
}

// HasClientCount returns a boolean if a field has been set.
func (o *TagUsage) HasClientCount() bool {
	if o != nil && !IsNil(o.ClientCount) {
		return true
	}

	return false
}

// SetClientCount gets a reference to the given int64 and assigns it to the ClientCount field.
func (o *TagUsage) SetClientCount(v int64) {
	o.ClientCount = &v
}

// GetClientIds returns the ClientIds field value if set, zero value otherwise.
func (o *TagUsage) GetClientIds() []string {
	if o == nil || IsNil(o.ClientIds) {
		var ret []string
		return ret
	}
	return o.ClientIds
}

// GetClientIdsOk returns a tuple with the ClientIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagUsage) GetClientIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ClientIds) {
		return nil, false
	}
	return o.ClientIds, true
}

// HasClientIds returns a boolean if a field has been set.
func (o *TagUsage) HasClientIds() bool {
	if o != nil && !IsNil(o.ClientIds) {
		return true
	}

	return false
}

// SetClientIds gets a reference to the given []string and assigns it to the ClientIds field.
func (o *TagUsage) SetClientIds(v []string) {
	o.ClientIds = v
}

// GetSelectorInstances returns the SelectorInstances field value if set, zero value otherwise.
func (o *TagUsage) GetSelectorInstances() []ReferenceItem {
	if o == nil || IsNil(o.SelectorInstances) {
		var ret []ReferenceItem
		return ret
	}
	return o.SelectorInstances
}

// GetSelectorInstancesOk returns a tuple with the SelectorInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagUsage) GetSelectorInstancesOk() ([]ReferenceItem, bool) {
	if o == nil || IsNil(o.SelectorInstances) {
		return nil, false
	}
	return o.SelectorInstances, true
}

// HasSelectorInstances returns a boolean if a field has been set.
func (o *TagUsage) HasSelectorInstances() bool {
	if o != nil && !IsNil(o.SelectorInstances) {
		return true
	}

	return false
}

// SetSelectorInstances gets a reference to the given []ReferenceItem and assigns it to the SelectorInstances field.
func (o *TagUsage) SetSelectorInstances(v []ReferenceItem) {
	o.SelectorInstances = v
}

// GetCimdPolicies returns the CimdPolicies field value if set, zero value otherwise.
func (o *TagUsage) GetCimdPolicies() []ReferenceItem {
	if o == nil || IsNil(o.CimdPolicies) {
		var ret []ReferenceItem
		return ret
	}
	return o.CimdPolicies
}

// GetCimdPoliciesOk returns a tuple with the CimdPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagUsage) GetCimdPoliciesOk() ([]ReferenceItem, bool) {
	if o == nil || IsNil(o.CimdPolicies) {
		return nil, false
	}
	return o.CimdPolicies, true
}

// HasCimdPolicies returns a boolean if a field has been set.
func (o *TagUsage) HasCimdPolicies() bool {
	if o != nil && !IsNil(o.CimdPolicies) {
		return true
	}

	return false
}

// SetCimdPolicies gets a reference to the given []ReferenceItem and assigns it to the CimdPolicies field.
func (o *TagUsage) SetCimdPolicies(v []ReferenceItem) {
	o.CimdPolicies = v
}

// GetClientSettingsUsed returns the ClientSettingsUsed field value if set, zero value otherwise.
func (o *TagUsage) GetClientSettingsUsed() bool {
	if o == nil || IsNil(o.ClientSettingsUsed) {
		var ret bool
		return ret
	}
	return *o.ClientSettingsUsed
}

// GetClientSettingsUsedOk returns a tuple with the ClientSettingsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagUsage) GetClientSettingsUsedOk() (*bool, bool) {
	if o == nil || IsNil(o.ClientSettingsUsed) {
		return nil, false
	}
	return o.ClientSettingsUsed, true
}

// HasClientSettingsUsed returns a boolean if a field has been set.
func (o *TagUsage) HasClientSettingsUsed() bool {
	if o != nil && !IsNil(o.ClientSettingsUsed) {
		return true
	}

	return false
}

// SetClientSettingsUsed gets a reference to the given bool and assigns it to the ClientSettingsUsed field.
func (o *TagUsage) SetClientSettingsUsed(v bool) {
	o.ClientSettingsUsed = &v
}

func (o TagUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientCount) {
		toSerialize["clientCount"] = o.ClientCount
	}
	if !IsNil(o.ClientIds) {
		toSerialize["clientIds"] = o.ClientIds
	}
	if !IsNil(o.SelectorInstances) {
		toSerialize["selectorInstances"] = o.SelectorInstances
	}
	if !IsNil(o.CimdPolicies) {
		toSerialize["cimdPolicies"] = o.CimdPolicies
	}
	if !IsNil(o.ClientSettingsUsed) {
		toSerialize["clientSettingsUsed"] = o.ClientSettingsUsed
	}
	return toSerialize, nil
}

type NullableTagUsage struct {
	value *TagUsage
	isSet bool
}

func (v NullableTagUsage) Get() *TagUsage {
	return v.value
}

func (v *NullableTagUsage) Set(val *TagUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableTagUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableTagUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagUsage(val *TagUsage) *NullableTagUsage {
	return &NullableTagUsage{value: val, isSet: true}
}

func (v NullableTagUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
