/*
Administrative API Documentation

The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the LocalIdentityProfiles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalIdentityProfiles{}

// LocalIdentityProfiles A collection of local identity profiles.
type LocalIdentityProfiles struct {
	// The actual list of local identity profiles.
	Items []LocalIdentityProfile `json:"items,omitempty" tfsdk:"items"`
}

// NewLocalIdentityProfiles instantiates a new LocalIdentityProfiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalIdentityProfiles() *LocalIdentityProfiles {
	this := LocalIdentityProfiles{}
	return &this
}

// NewLocalIdentityProfilesWithDefaults instantiates a new LocalIdentityProfiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalIdentityProfilesWithDefaults() *LocalIdentityProfiles {
	this := LocalIdentityProfiles{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *LocalIdentityProfiles) GetItems() []LocalIdentityProfile {
	if o == nil || IsNil(o.Items) {
		var ret []LocalIdentityProfile
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalIdentityProfiles) GetItemsOk() ([]LocalIdentityProfile, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *LocalIdentityProfiles) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []LocalIdentityProfile and assigns it to the Items field.
func (o *LocalIdentityProfiles) SetItems(v []LocalIdentityProfile) {
	o.Items = v
}

func (o LocalIdentityProfiles) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalIdentityProfiles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableLocalIdentityProfiles struct {
	value *LocalIdentityProfiles
	isSet bool
}

func (v NullableLocalIdentityProfiles) Get() *LocalIdentityProfiles {
	return v.value
}

func (v *NullableLocalIdentityProfiles) Set(val *LocalIdentityProfiles) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalIdentityProfiles) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalIdentityProfiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalIdentityProfiles(val *LocalIdentityProfiles) *NullableLocalIdentityProfiles {
	return &NullableLocalIdentityProfiles{value: val, isSet: true}
}

func (v NullableLocalIdentityProfiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalIdentityProfiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
